--DROP TABLES
DROP TABLE "Account" CASCADE CONSTRAINTS;
DROP TABLE Huurder CASCADE CONSTRAINTS;
DROP TABLE HuurContract CASCADE CONSTRAINTS;
DROP TABLE Artikel CASCADE CONSTRAINTS;
DROP TABLE Boot CASCADE CONSTRAINTS;
DROP TABLE Waterlichaam CASCADE CONSTRAINTS;
DROP TABLE Huur_Artikelen CASCADE CONSTRAINTS;
DROP TABLE Huur_Boten CASCADE CONSTRAINTS;
DROP TABLE Huur_Waterlichaam CASCADE CONSTRAINTS;
DROP TABLE MotorBoot CASCADE CONSTRAINTS;
DROP TABLE SpierBoot CASCADE CONSTRAINTS;

--CREATE TABLES AND ADD PRIMARY KEYS
Create Table "Account"
(
  ID Number(10) Primary Key,
  Naam Varchar2(32) Not Null Unique,
  Email Varchar2(32) Not Null Unique,
  Wachtwoord VARCHAR2(32) NOT NULL
);

CREATE TABLE Huurder
(
	ID		NUMBER(10)		PRIMARY KEY,
	Naam	VARCHAR2(32)	NOT NULL,
	Email	VARCHAR2(32)	NOT NULL UNIQUE,
);

CREATE TABLE HuurContract
(
	ID				NUMBER(10)		PRIMARY KEY,
	BeginTijd		DATE		NOT NULL,
	EindTijd		DATE		NOT NULL,
	Huurder_ID		NUMBER(10)	NOT NULL,
	Verhuurder_ID	NUMBER(10)	NOT NULL
);

CREATE TABLE Artikel
(
	ID		NUMBER(10)		PRIMARY KEY,
	Naam	VARCHAR2(64)	NOT NULL UNIQUE,
	Prijs	NUMBER(10, 2)	NOT NULL
);

CREATE TABLE Boot
(
	Naam		VARCHAR(64)		PRIMARY KEY,
	DagPrijs	NUMBER(10,2)	NOT NULL,
	BootType	VARCHAR(64)		NOT NULL CHECK(BootType = 'MotorBoot' or BootType = 'SpierBoot')
);

CREATE TABLE Waterlichaam
(
	ID		NUMBER(10)		PRIMARY KEY,
	Naam	VARCHAR2(64)	
);

CREATE TABLE Huur_Artikelen
(
	HuurContract_ID	NUMBER(10)	NOT NULL,
	Artikel_ID		NUMBER(10)	NOT NULL,
	
	PRIMARY KEY(HuurContract_ID, Artikel_ID)
);

CREATE TABLE Huur_Boten
(
	HuurContract_ID	NUMBER(10)	NOT NULL,
	Boot_Naam		VARCHAR(64)	NOT NULL,
	
	PRIMARY KEY(HuurContract_ID, Boot_Naam)
);

CREATE TABLE Huur_Waterlichaam
(
	HuurContract_ID	NUMBER(10)	NOT NULL,
	Waterlichaam_ID		NUMBER(10)	NOT NULL,
	
	PRIMARY KEY(HuurContract_ID, Waterlichaam_ID)
);

CREATE TABLE MotorBoot
(
	Naam		VARCHAR(64)		PRIMARY KEY,
	"Type"		VARCHAR2(64)	NOT NULL,
	TankInhoud	NUMBER(10, 2)	NOT NULL
);

CREATE TABLE SpierBoot
(
	Naam		VARCHAR(64)		PRIMARY KEY,
	"Type"		VARCHAR2(64)	NOT NULL
);


ALTER TABLE HuurContract ADD FOREIGN KEY (Verhuurder_ID)	REFERENCES	"Account"(ID);
ALTER TABLE HuurContract ADD FOREIGN KEY (Huurder_ID)	REFERENCES	Huurder(ID);
ALTER TABLE Huur_Artikelen ADD FOREIGN KEY (HuurContract_ID)	REFERENCES HuurContract(ID);
ALTER TABLE Huur_Artikelen	ADD FOREIGN KEY (Artikel_ID)	REFERENCES	Artikel(ID);
ALTER TABLE Huur_Boten		ADD FOREIGN KEY (HuurContract_ID) REFERENCES HuurContract(ID);
ALTER TABLE Huur_Boten		ADD FOREIGN KEY (Boot_Naam)		REFERENCES Boot(Naam);
ALTER TABLE Huur_Waterlichaam	ADD FOREIGN KEY(HuurContract_ID)	REFERENCES HuurContract(ID);
ALTER TABLE Huur_Waterlichaam	ADD FOREIGN KEY(Waterlichaam_ID)	REFERENCES Waterlichaam(ID);	
ALTER TABLE MotorBoot ADD FOREIGN KEY (Naam)	REFERENCES	Boot(Naam);
ALTER TABLE SpierBoot ADD FOREIGN KEY (Naam)	REFERENCES	Boot(Naam);
