--DROP TABLES
DROP TABLE "Account" CASCADE CONSTRAINTS;
DROP TABLE Huurder CASCADE CONSTRAINTS;
DROP TABLE HuurContract CASCADE CONSTRAINTS;
DROP TABLE Artikel CASCADE CONSTRAINTS;
DROP TABLE Boot CASCADE CONSTRAINTS;
DROP TABLE Waterlichaam CASCADE CONSTRAINTS;
DROP TABLE Huur_Artikelen CASCADE CONSTRAINTS;
DROP TABLE Huur_Boten CASCADE CONSTRAINTS;
DROP TABLE Huur_Waterlichaam CASCADE CONSTRAINTS;
DROP TABLE MotorBoot CASCADE CONSTRAINTS;
DROP TABLE SpierBoot CASCADE CONSTRAINTS;

--CREATE TABLES AND ADD PRIMARY KEYS
Create Table "Account"
(
  ID Number(10) Primary Key,
  Naam Varchar2(32) Not Null Unique,
  Email Varchar2(32) Not Null Unique,
  Wachtwoord VARCHAR2(32) NOT NULL
);

CREATE TABLE Huurder
(
	ID		NUMBER(10)		PRIMARY KEY,
	Naam	VARCHAR2(32)	NOT NULL,
	Email	VARCHAR2(32)	NOT NULL UNIQUE,
);

CREATE TABLE Artikel
(
	ID		NUMBER(10)		PRIMARY KEY,
	Naam	VARCHAR2(64)	NOT NULL UNIQUE,
	Prijs	NUMBER(10, 2)	NOT NULL
);

CREATE TABLE Boot
(
	Naam		VARCHAR(64)		PRIMARY KEY,
	DagPrijs	NUMBER(10,2)	NOT NULL,
	BootType	VARCHAR(64)		NOT NULL CHECK(BootType = 'MotorBoot' or BootType = 'SpierBoot')
);

CREATE TABLE Waterlichaam
(
	ID		NUMBER(10)		PRIMARY KEY,
	Naam	VARCHAR2(64)	
);

CREATE TABLE Huur_Artikelen
(
	HuurContract_ID	NUMBER(10)	NOT NULL,
	Artikel_ID		NUMBER(10)	NOT NULL,
	
	PRIMARY KEY(HuurContract_ID, Artikel_ID)
);

CREATE TABLE Huur_Boten
(
	HuurContract_ID	NUMBER(10)	NOT NULL,
	Boot_ID			NUMBER(10)	NOT NULL,
	
	PRIMARY KEY(HuurContract_ID, Boot_ID)
);

CREATE TABLE Huur_Waterlichaam
(
	HuurContract_ID	NUMBER(10)	NOT NULL,
	Waterlichaam_ID		NUMBER(10)	NOT NULL,
	
	PRIMARY KEY(HuurContract_ID, Waterlichaam_ID)
);

CREATE TABLE MotorBoot
(
	Naam		VARCHAR(64)		PRIMARY KEY,
	"Type"		VARCHAR2(64)	NOT NULL,
	TankInhoud	NUMBER(10, 2)	NOT NULL
);

CREATE TABLE SpierBoot
(
	Naam		VARCHAR(64)		PRIMARY KEY,
	"Type"		VARCHAR2(64)	NOT NULL
);
